---
engines:
  fixme:
    enabled: true
  cppcheck:
    enabled: true
    config:
      check: all
      inconclusive: false
      stds:
        - c++11
        - posix
ratings:
  paths: []
exclude_paths:
- tests/
