compiler:
  - clang++
language: cpp
script: ./autogen.sh && ./configure && make && make check


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "qRLxcWFwwnNpCQ5zFY7DDGMOP51pe6G6+Ub5UKCEJyqUupAmMVD1PmKwBFhYk5WKSa501Hi61+VhmrzOicomN8M1t7r7OLhJdhg6qmKRkEe68T1Y2T138KDjaGrRV9tnJxZdPWbRs0svqVqbikm7HQ30MBk+lcoUYvNVzjHtUOav10+Z5ulrkXXTlaNBYdO6k+hD8bJjto+7UNrPBgGwSpnMOovt9LU/czXYmLJvx08c/CFi3SR3wmglvFYE3XCbuoHXHKExUYhOcuYXmh3r6sbcobdIfMAroQGUQ3Nxh5N+y7IqSCaea6VEbED6scNz7L6UlZGAtuLC9GkIVcGKZ+0gxIMYqIQZzXAe+hmRj+/2Pze9kstjL0yVyRz62gBQKIxmzGYCX680CLaf0YsOUX88f/0cnqc0zXZBbHYgfCcfQTqLSl7bkU6sTTy8aaeN++ReWgpNq+mXA/hGy11JOUCQnZkSmnYW35KyR3bunBrielDVJ1hYIenQGLbYuwD6M9WvcPVJwgfnPv35GuRtWZNheJFCWe4Xs7qbk0dBnv6MiZx+3yoEsuQUwen/frtrNH5bgXvc4ocUdvMatlrEr0dFfzwUSwvpRjaxFU0Kk5if5uhdn+0MFTvtb27MLBhqKgJ9eu0lC3nzJxbysJ8eVdJE7USA+jTFkuJK0x1ibzo="

addons:
  coverity_scan:
    project:
      name: "quayle/command"
      description: "Build submitted via Travis CI"
    notification_email: dlugolecki.rafal@gmail.com
    build_command_prepend: "./autogen.sh ; ./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  code_climate:
        repo_token: 7c7ce5ba21e7889b416fa1e0be9ce9f293021c706ec99a099d965e26a2a23386